// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiV2nqSeUve6-HaC2GIz6kea-JvkTyIQ0',
    appId: '1:257276967770:android:5183902c4c3d0a84cf9163',
    messagingSenderId: '257276967770',
    projectId: 'primal-aggregated-banking-app',
    storageBucket: 'primal-aggregated-banking-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrVY1CmR8KogFsO5mxwxvKmBr7diNqCXU',
    appId: '1:257276967770:ios:5daf9d5826d93491cf9163',
    messagingSenderId: '257276967770',
    projectId: 'primal-aggregated-banking-app',
    storageBucket: 'primal-aggregated-banking-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );
}